name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-saas-stack-db"
database_id = "157936c4-a6d1-40f5-bd0f-4065aa85f5c1"
migrations_dir = "./drizzle"
